fullnameOverride: ak-homepage
replicaCount: 1
image:
  repository: akprodcr.azurecr.io/ak-homepage
  tag: "1.0"
  pullPolicy: IfNotPresent
  pullSecrets:
  - name: ak-prod-image-pull-secret
service:
  type: ClusterIP
  port: 80
probes:
  enabled: true
  liveness:
    tcpPort: 80
    initialDelaySeconds: 30
    periodSeconds: 60
    failureThreshold: 5
    timeoutSeconds: 60
  readiness:
    httpGetPath: /health
    initialDelaySeconds: 30
    periodSeconds: 60
    failureThreshold: 5
    timeoutSeconds: 60
configPath: /config
secrets:
  version: "1.0"
  path: /secrets
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi