FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build
WORKDIR /src
ARG PROJECT_NAME=AK.Homepage
COPY ["src/${PROJECT_NAME}.csproj", "/src/"]
RUN dotnet restore "${PROJECT_NAME}.csproj"
COPY src/ ./
RUN dotnet build "${PROJECT_NAME}.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AK.Homepage.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0
WORKDIR /app
ENV AK_RUNNING_IN_CONTAINER True
ENV AK_LISTEN_PORT 80
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AK.Homepage.dll"]