apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-config
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  BlogListAddress: https://api.github.com/repos/aashishkoirala/aashishkoirala.github.io/contents/blog-content
  BlogContentBaseAddress: https://raw.githubusercontent.com/aashishkoirala/aashishkoirala.github.io/master/blog-content/
  SlugifyRemovalList: '~`!@#$%^&*()_+=[]{}\\|;:''\",<.>/?'
  SlugifyReplacementMap: " c#-> csharp|c# ->csharp | C#-> csharp|C# ->csharp | .net-> dotnet|.net ->dotnet | .NET-> dotnet|.NET ->dotnet | f#-> fsharp|f# ->fsharp | F#-> fsharp|F# ->fsharp "
  HomeLinkCount: "15"
  RssItemCount: "20"
  HttpCachePathEqualsList: "/,/resume,/about,/sitemap"
  HttpCachePathStartsWithList: "/blog,/rss"