CREATE TABLE PageAccess (
    Id INT IDENTITY (1, 1) NOT NULL CONSTRAINT PK_PageAccess PRIMARY KEY,
    [TimeStamp] DATETIMEOFFSET NOT NULL CONSTRAINT DF_PageAccess_TimeStamp DEFAULT GETUTCDATE(),
    [Path] VARCHAR (255) NOT NULL,
    [IpAddress] VARCHAR(50) NOT NULL,
    [UserAgent] VARCHAR(100) NOT NULL
)
